# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faasfunc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='faasfunc.proto',
  package='Funcbench',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x66\x61\x61sfunc.proto\x12\tFuncbench\"\x1d\n\rInvokeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0bInvokeReply\x12\x0f\n\x07message\x18\x01 \x01(\t2L\n\x08\x46\x61\x61SFunc\x12@\n\nInvokeFunc\x12\x18.Funcbench.InvokeRequest\x1a\x16.Funcbench.InvokeReply\"\x00\x62\x06proto3'
)




_INVOKEREQUEST = _descriptor.Descriptor(
  name='InvokeRequest',
  full_name='Funcbench.InvokeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Funcbench.InvokeRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=58,
)


_INVOKEREPLY = _descriptor.Descriptor(
  name='InvokeReply',
  full_name='Funcbench.InvokeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='Funcbench.InvokeReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['InvokeRequest'] = _INVOKEREQUEST
DESCRIPTOR.message_types_by_name['InvokeReply'] = _INVOKEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InvokeRequest = _reflection.GeneratedProtocolMessageType('InvokeRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOKEREQUEST,
  '__module__' : 'faasfunc_pb2'
  # @@protoc_insertion_point(class_scope:Funcbench.InvokeRequest)
  })
_sym_db.RegisterMessage(InvokeRequest)

InvokeReply = _reflection.GeneratedProtocolMessageType('InvokeReply', (_message.Message,), {
  'DESCRIPTOR' : _INVOKEREPLY,
  '__module__' : 'faasfunc_pb2'
  # @@protoc_insertion_point(class_scope:Funcbench.InvokeReply)
  })
_sym_db.RegisterMessage(InvokeReply)



_FAASFUNC = _descriptor.ServiceDescriptor(
  name='FaaSFunc',
  full_name='Funcbench.FaaSFunc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=92,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='InvokeFunc',
    full_name='Funcbench.FaaSFunc.InvokeFunc',
    index=0,
    containing_service=None,
    input_type=_INVOKEREQUEST,
    output_type=_INVOKEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAASFUNC)

DESCRIPTOR.services_by_name['FaaSFunc'] = _FAASFUNC

# @@protoc_insertion_point(module_scope)
